# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here - obraz dockerowy zostanie postawiony w tej wersji, żeby wykonywać testy
      - image: circleci/openjdk:8-jdk
        environment: #zmienne potrzebne do zintegrowania javy z bazą danych
          JDBC_DATABASE_URL: jdbc:postgresql://localhost:5432/ci-course?useSSL=false&serverTimezone=UTC
          JDBC_DATABASE_USERNAME: root
          JDBC_DATABASE_PASSWORD: root

     #kontener bazy danych
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_DB: ci-course

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/ci-course-java

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies - żeby nie trzeba było za każdym razem ściągać zależności
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn test  